In [109]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',None)

In [110]:
data = pd.read_csv(r"C:\Users\Mishra\Downloads\archive\matches.csv",header=0,index_col=0)
data.head()

date           time            comp        round  day venue result  \
0  2020-09-21  20:15 (21:15)  Premier League  Matchweek 2  Mon  Away      W   
2  2020-09-27  16:30 (17:30)  Premier League  Matchweek 3  Sun  Home      L   
4  2020-10-03  17:30 (18:30)  Premier League  Matchweek 4  Sat  Away      D   
5  2020-10-17  17:30 (18:30)  Premier League  Matchweek 5  Sat  Home      W   
7  2020-10-24  12:30 (13:30)  Premier League  Matchweek 6  Sat  Away      D   

   gf  ga        opponent   xg  xga  poss  attendance          captain  \
0   3   1          Wolves  1.9  0.6    65         NaN      Fernandinho   
2   2   5  Leicester City  0.9  2.9    72         NaN      Fernandinho   
4   1   1    Leeds United  1.2  2.4    49         NaN  Kevin De Bruyne   
5   1   0         Arsenal  1.3  0.9    58         NaN  Raheem Sterling   
7   1   1        West Ham  1.0  0.3    69         NaN  Raheem Sterling   

  formation         referee  match report  notes  sh  sot  dist  fk  pk  \
0   4-2-3-1  Andre Marriner  Match Report    NaN  13    8  21.1   2   1   
2   4-2-3-1  Michael Oliver  Match Report    NaN  16    5  19.8   1   0   
4     4-3-3       Mike Dean  Match Report    NaN  23    1  18.2   1   0   
5   3-1-4-2  Chris Kavanagh  Match Report    NaN  13    5  17.7   0   0   
7     4-3-3  Anthony Taylor  Match Report    NaN  14    7  20.9   1   0   

   pkatt  season             team  
0      1    2024  Manchester City  
2      0    2024  Manchester City  
4      0    2024  Manchester City  
5      0    2024  Manchester City  
7      0    2024  Manchester City

<!-- Features description
date : the date of the game
time : the time of the game
comp : the competition of the game
round : the round of the game
day : the day of the week of the game
venue : the venue of the game
result : the result of the game
gf : the goals for the home team
ga : the goals for the away team
opponent: the opponent of the home team
xg : the expected goals for the home team
xga : the expected goals for the away team
poss : the possession of the home team
captain : the captain of the home team
formation : the formation of the home team
referee : the referee of the game
sh : the shots of the home team
sot : the shots on target of the home team
dist : the average distance of the shots of the home team
fk : the free kicks of the home team
pk : the penalty kicks of the home team
pka : the penalty kicks attempted of the home team
season : the season year of the match
team: the home team -->

In [111]:
data1 = data.copy()
data1.head()

date           time            comp        round  day venue result  \
0  2020-09-21  20:15 (21:15)  Premier League  Matchweek 2  Mon  Away      W   
2  2020-09-27  16:30 (17:30)  Premier League  Matchweek 3  Sun  Home      L   
4  2020-10-03  17:30 (18:30)  Premier League  Matchweek 4  Sat  Away      D   
5  2020-10-17  17:30 (18:30)  Premier League  Matchweek 5  Sat  Home      W   
7  2020-10-24  12:30 (13:30)  Premier League  Matchweek 6  Sat  Away      D   

   gf  ga        opponent   xg  xga  poss  attendance          captain  \
0   3   1          Wolves  1.9  0.6    65         NaN      Fernandinho   
2   2   5  Leicester City  0.9  2.9    72         NaN      Fernandinho   
4   1   1    Leeds United  1.2  2.4    49         NaN  Kevin De Bruyne   
5   1   0         Arsenal  1.3  0.9    58         NaN  Raheem Sterling   
7   1   1        West Ham  1.0  0.3    69         NaN  Raheem Sterling   

  formation         referee  match report  notes  sh  sot  dist  fk  pk  \
0   4-2-3-1  Andre Marriner  Match Report    NaN  13    8  21.1   2   1   
2   4-2-3-1  Michael Oliver  Match Report    NaN  16    5  19.8   1   0   
4     4-3-3       Mike Dean  Match Report    NaN  23    1  18.2   1   0   
5   3-1-4-2  Chris Kavanagh  Match Report    NaN  13    5  17.7   0   0   
7     4-3-3  Anthony Taylor  Match Report    NaN  14    7  20.9   1   0   

   pkatt  season             team  
0      1    2024  Manchester City  
2      0    2024  Manchester City  
4      0    2024  Manchester City  
5      0    2024  Manchester City  
7      0    2024  Manchester City

In [112]:
data1.drop(['time','comp','round','venue','attendance','match report','notes','referee','captain'],axis=1,inplace=True)

In [113]:
data1.head()

date  day result  gf  ga        opponent   xg  xga  poss formation  \
0  2020-09-21  Mon      W   3   1          Wolves  1.9  0.6    65   4-2-3-1   
2  2020-09-27  Sun      L   2   5  Leicester City  0.9  2.9    72   4-2-3-1   
4  2020-10-03  Sat      D   1   1    Leeds United  1.2  2.4    49     4-3-3   
5  2020-10-17  Sat      W   1   0         Arsenal  1.3  0.9    58   3-1-4-2   
7  2020-10-24  Sat      D   1   1        West Ham  1.0  0.3    69     4-3-3   

   sh  sot  dist  fk  pk  pkatt  season             team  
0  13    8  21.1   2   1      1    2024  Manchester City  
2  16    5  19.8   1   0      0    2024  Manchester City  
4  23    1  18.2   1   0      0    2024  Manchester City  
5  13    5  17.7   0   0      0    2024  Manchester City  
7  14    7  20.9   1   0      0    2024  Manchester City

In [114]:
data1.shape

(4788, 18)

In [115]:
data1.describe()

gf           ga           xg          xga         poss  \
count  4788.000000  4788.000000  4788.000000  4788.000000  4788.000000   
mean      1.447995     1.405388     1.396512     1.364745    50.432957   
std       1.312635     1.286927     0.828847     0.814947    12.810958   
min       0.000000     0.000000     0.000000     0.000000    18.000000   
25%       0.000000     0.000000     0.800000     0.700000    41.000000   
50%       1.000000     1.000000     1.300000     1.200000    51.000000   
75%       2.000000     2.000000     1.900000     1.800000    60.000000   
max       9.000000     9.000000     7.000000     7.000000    82.000000   

                sh          sot         dist           fk           pk  \
count  4788.000000  4788.000000  4786.000000  4788.000000  4788.000000   
mean     12.619256     4.261278    17.356247     0.453216     0.118212   
std       5.548444     2.459963     3.049341     0.665250     0.342362   
min       0.000000     0.000000     5.300000     0.000000     0.000000   
25%       9.000000     2.000000    15.400000     0.000000     0.000000   
50%      12.000000     4.000000    17.200000     0.000000     0.000000   
75%      16.000000     6.000000    19.100000     1.000000     0.000000   
max      36.000000    15.000000    39.900000     4.000000     3.000000   

            pkatt       season  
count  4788.00000  4788.000000  
mean      0.14599  2022.365079  
std       0.37937     1.461850  
min       0.00000  2020.000000  
25%       0.00000  2021.000000  
50%       0.00000  2023.000000  
75%       0.00000  2024.000000  
max       3.00000  2024.000000

In [116]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4788 entries, 0 to 91
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   date       4788 non-null   object 
 1   day        4788 non-null   object 
 2   result     4788 non-null   object 
 3   gf         4788 non-null   int64  
 4   ga         4788 non-null   int64  
 5   opponent   4788 non-null   object 
 6   xg         4788 non-null   float64
 7   xga        4788 non-null   float64
 8   poss       4788 non-null   int64  
 9   formation  4788 non-null   object 
 10  sh         4788 non-null   int64  
 11  sot        4788 non-null   int64  
 12  dist       4786 non-null   float64
 13  fk         4788 non-null   int64  
 14  pk         4788 non-null   int64  
 15  pkatt      4788 non-null   int64  
 16  season     4788 non-null   int64  
 17  team       4788 non-null   object 
dtypes: float64(3), int64(9), object(6)
memory usage: 710.7+ KB


In [117]:
data1.isnull().sum()

date         0
day          0
result       0
gf           0
ga           0
opponent     0
xg           0
xga          0
poss         0
formation    0
sh           0
sot          0
dist         2
fk           0
pk           0
pkatt        0
season       0
team         0
dtype: int64

In [118]:
data1['dist'].fillna(data1['dist'].median(),inplace=True)

In [119]:
data1.isnull().sum()

date         0
day          0
result       0
gf           0
ga           0
opponent     0
xg           0
xga          0
poss         0
formation    0
sh           0
sot          0
dist         0
fk           0
pk           0
pkatt        0
season       0
team         0
dtype: int64

In [120]:
data1.duplicated().sum()

0

In [121]:
data1["date"] = pd.to_datetime(data1["date"])

In [122]:
data1.formation.value_counts()

formation
4-2-3-1       1382
4-3-3         1025
4-4-2          583
3-4-3          548
3-5-2          266
4-1-4-1        258
4-4-1-1        141
3-4-1-2        113
5-3-2          107
5-4-1           99
4-5-1           49
4-3-1-2         47
4-1-2-1-2◆      35
4-2-2-2         29
3-1-4-2         25
4-3-2-1         22
3-2-4-1         21
3-3-3-1         17
3-5-1-1         14
3-4-3◆           3
4-1-3-2          2
4-2-4-0          2
Name: count, dtype: int64

In [123]:
data1.formation = data1.formation.str.replace('◆', '')
data1.formation = data1.formation.replace('-0','')

In [124]:
data1.formation.value_counts()

formation
4-2-3-1      1382
4-3-3        1025
4-4-2         583
3-4-3         551
3-5-2         266
4-1-4-1       258
4-4-1-1       141
3-4-1-2       113
5-3-2         107
5-4-1          99
4-5-1          49
4-3-1-2        47
4-1-2-1-2      35
4-2-2-2        29
3-1-4-2        25
4-3-2-1        22
3-2-4-1        21
3-3-3-1        17
3-5-1-1        14
4-1-3-2         2
4-2-4-0         2
Name: count, dtype: int64

In [125]:
data1.season.value_counts()

season
2024    1520
2023     988
2022     760
2021     760
2020     760
Name: count, dtype: int64

In [126]:
data2 = data1.columns
data2 = data2.drop('season')
data2

Index(['date', 'day', 'result', 'gf', 'ga', 'opponent', 'xg', 'xga', 'poss',
       'formation', 'sh', 'sot', 'dist', 'fk', 'pk', 'pkatt', 'team'],
      dtype='object')

In [127]:
data1.duplicated(subset=data2).sum()

988

In [128]:
data1.drop_duplicates(subset=data2, inplace=True)

In [129]:
data1.duplicated(subset=data2).sum()

0

In [130]:
def correct_seasons(data1):
    def get_correct_season(date):
        if date.month >= 8:
            return date.year + 1
        else:
            return date.year

    data1['season'] = data1['date'].apply(get_correct_season)
    return data1

In [131]:
data1 = correct_seasons(data1)
data1['season'].value_counts().sort_index()

season
2020    760
2021    760
2022    760
2023    760
2024    760
Name: count, dtype: int64

In [132]:
data1.result.replace({'L':-1,'W':1,'D':0},inplace=True)

In [133]:
data1.head()

date  day  result  gf  ga        opponent   xg  xga  poss formation  \
0 2020-09-21  Mon       1   3   1          Wolves  1.9  0.6    65   4-2-3-1   
2 2020-09-27  Sun      -1   2   5  Leicester City  0.9  2.9    72   4-2-3-1   
4 2020-10-03  Sat       0   1   1    Leeds United  1.2  2.4    49     4-3-3   
5 2020-10-17  Sat       1   1   0         Arsenal  1.3  0.9    58   3-1-4-2   
7 2020-10-24  Sat       0   1   1        West Ham  1.0  0.3    69     4-3-3   

   sh  sot  dist  fk  pk  pkatt  season             team  
0  13    8  21.1   2   1      1    2021  Manchester City  
2  16    5  19.8   1   0      0    2021  Manchester City  
4  23    1  18.2   1   0      0    2021  Manchester City  
5  13    5  17.7   0   0      0    2021  Manchester City  
7  14    7  20.9   1   0      0    2021  Manchester City

In [134]:
data1 = data1.assign(  day = data1.date.dt.day,
                        month = data1.date.dt.month, 
                        year = data1.date.dt.year )

In [135]:
data1.drop('date',axis=1,inplace=True)

In [136]:
data1.head()

day  result  gf  ga        opponent   xg  xga  poss formation  sh  sot  \
0   21       1   3   1          Wolves  1.9  0.6    65   4-2-3-1  13    8   
2   27      -1   2   5  Leicester City  0.9  2.9    72   4-2-3-1  16    5   
4    3       0   1   1    Leeds United  1.2  2.4    49     4-3-3  23    1   
5   17       1   1   0         Arsenal  1.3  0.9    58   3-1-4-2  13    5   
7   24       0   1   1        West Ham  1.0  0.3    69     4-3-3  14    7   

   dist  fk  pk  pkatt  season             team  month  year  
0  21.1   2   1      1    2021  Manchester City      9  2020  
2  19.8   1   0      0    2021  Manchester City      9  2020  
4  18.2   1   0      0    2021  Manchester City     10  2020  
5  17.7   0   0      0    2021  Manchester City     10  2020  
7  20.9   1   0      0    2021  Manchester City     10  2020

In [137]:
data1.formation.nunique()

21

In [138]:
data1['formation'] = data1['formation'].astype('category')

In [139]:
data1.dtypes

day             int32
result          int64
gf              int64
ga              int64
opponent       object
xg            float64
xga           float64
poss            int64
formation    category
sh              int64
sot             int64
dist          float64
fk              int64
pk              int64
pkatt           int64
season          int64
team           object
month           int32
year            int32
dtype: object

In [140]:
#Label Encoder



In [141]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data1["opponent"]=le.fit_transform(data1["opponent"])
data1["team"]=le.fit_transform(data1["team"])
# data1["result"]=le.fit_transform(data1["result"])
data1["formation"]=le.fit_transform(data1["formation"])

In [142]:
data1.head()

day  result  gf  ga  opponent   xg  xga  poss  formation  sh  sot  dist  \
0   21       1   3   1        25  1.9  0.6    65         11  13    8  21.1   
2   27      -1   2   5        11  0.9  2.9    72         11  16    5  19.8   
4    3       0   1   1        10  1.2  2.4    49         15  23    1  18.2   
5   17       1   1   0         0  1.3  0.9    58          0  13    5  17.7   
7   24       0   1   1        24  1.0  0.3    69         15  14    7  20.9   

   fk  pk  pkatt  season  team  month  year  
0   2   1      1    2021    14      9  2020  
2   1   0      0    2021    14      9  2020  
4   1   0      0    2021    14     10  2020  
5   0   0      0    2021    14     10  2020  
7   1   0      0    2021    14     10  2020

In [143]:
# X = data1.drop(['result'],axis=1)
# Y = data1.result

X = data1.drop(columns=['result']).values  # Features
Y = data1['result'].values

In [144]:
print(X.shape)
print(Y.shape)

(3800, 18)
(3800,)


In [145]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=10)

In [146]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(3040, 18)
(3040,)
(760, 18)
(760,)


In [147]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train,Y_train)

LogisticRegression()

In [148]:
Y_pred = classifier.predict(X_test)

In [149]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[275  31  11]
 [ 42  62  47]
 [  5  40 247]]
Classification report: 
              precision    recall  f1-score   support

          -1       0.85      0.87      0.86       317
           0       0.47      0.41      0.44       151
           1       0.81      0.85      0.83       292

    accuracy                           0.77       760
   macro avg       0.71      0.71      0.71       760
weighted avg       0.76      0.77      0.76       760

Accuracy of the model:  0.7684210526315789


In [150]:
#DT

In [160]:
from sklearn.tree import DecisionTreeClassifier
model_dt = DecisionTreeClassifier(random_state=10,criterion='gini',splitter='best',min_samples_leaf=2,min_samples_split=3,max_depth=5)


model_dt.fit(X_train,Y_train)
Y_pred = model_dt.predict(X_test)


In [161]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[314   3   0]
 [  0 151   0]
 [  0   0 292]]
Classification report: 
              precision    recall  f1-score   support

          -1       1.00      0.99      1.00       317
           0       0.98      1.00      0.99       151
           1       1.00      1.00      1.00       292

    accuracy                           1.00       760
   macro avg       0.99      1.00      1.00       760
weighted avg       1.00      1.00      1.00       760

Accuracy of the model:  0.9960526315789474


In [162]:
model_dt.score(X_train,Y_train)

0.9927631578947368

In [166]:
classifier=DecisionTreeClassifier(random_state=10,criterion='gini',splitter='best',min_samples_leaf=2,min_samples_split=3,max_depth=5)
 
#performing kfold_cross_validation
from sklearn.model_selection import KFold
kfold_cv=KFold(n_splits=10,random_state=10,shuffle=True)
#print(kfold_cv)
 
from sklearn.model_selection import cross_val_score
#running the model using scoring metric as accuracy
kfold_cv_result=cross_val_score(estimator=classifier,X=X_train,
                                                 y=Y_train, cv=kfold_cv)
print(kfold_cv_result)
#finding the mean
print(kfold_cv_result.mean())

[0.99013158 0.99342105 0.99013158 0.99013158 0.99342105 0.99013158
 0.99013158 0.97697368 0.99013158 0.99342105]
0.9898026315789472


In [167]:
#model tuning
#perform only when CV can be used for tuning
for train_value, test_value in kfold_cv.split(X_train):
    classifier.fit(X_train[train_value], Y_train[train_value]).predict(X_train[test_value])
    
Y_pred=classifier.predict(X_test)

In [168]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
 
cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)
 
print("Classification report: ")
 
print(classification_report(Y_test,Y_pred))
 
acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[317   0   0]
 [  0 151   0]
 [  0   3 289]]
Classification report: 
              precision    recall  f1-score   support

          -1       1.00      1.00      1.00       317
           0       0.98      1.00      0.99       151
           1       1.00      0.99      0.99       292

    accuracy                           1.00       760
   macro avg       0.99      1.00      1.00       760
weighted avg       1.00      1.00      1.00       760

Accuracy of the model:  0.9960526315789474
